{% set name = "smeagol-bio" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: {{ data.get("version") }}

source:
  path: .

build:
  noarch: python  # not OS architecture dependent
  script: python -m pip install --no-deps .

channels:
  - bioconda
  - conda-forge

requirements:
  host:
    - python >=3.7
    - pip >=22.1.2
  run:
    - biopython>=1.79
    - h5py>=3.1.0 
    - keras>=2.4.3
    - numpy>=1.19.2
    - pandas>=1.2.5
    - pip>=22.1.2
    - python>=3.7
    - pytables>=3.6.1
    - pytest>=6.2.4
    - recommonmark>=0.7.1  
    - scikit-learn>=0.24.2
    - scipy>=1.7.0
    - seaborn>=0.11.1
    - seqlogo>=5.29.8
    - setuptools>=57.0.0
    - sphinx>=5.0.0
    - statsmodels>=0.12.2
    - tensorflow>=2.5.0
    - ushuffle>=1.1.2
