name: build

on: [push]

jobs:
  conda-installation:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: true
          auto-activate-base: true

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Build conda package
        shell: bash -l {0}
        run: |
          mamba install boa conda-verify -c conda-forge
          conda mambabuild . -c bioconda conda-forge

      - name: Activate the real base env and install conda package
        shell: bash -l {0}
        run: |
          conda deactivate
          conda install -c /usr/share/miniconda3/envs/test/conda-bld/noarch smeagol-bio -c bioconda -c conda-forge -y
          conda list
