name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy-PyPI:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools Cython twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

  publish-Conda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        subDir: '.'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
